version: 2.1

orbs:
  python: circleci/python@1.4

parameters:
  test-results-path:
    type: string
    default: "./testresults"
  coverage_report_file:
    type: string
    default: "/coverage.xml"
  test_report_file:
    type: string
    default: "/pytest-report.xml"

jobs:
  test-job-parameters:
    parameters:
      test2_report_file:
        type: string
        default: << pipeline.parameters.test-results-path >>/pytest-report.xml
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: echo << parameters.test2_report_file >>
  test-job-environment:
    environment:
      test1_report_file=<< pipeline.parameters.test-results-path >><< pipeline.parameters.coverage_report_file >>
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: echo $test1_report_file

workflows:
  sample:
    jobs:
      - test-job-parameters
      - test-job-environment
