version: 2.1

parameters:
  partner:
    type: string
    default: "Number1"
  env:
    type: string
    default: "one"

orbs:
  python: circleci/python@1.4


jobs:
  building-jobs:
    environment:
      PARTNER_FLAVOR: << pipeline.parameters.partner >>
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: echo "Building app for " << pipeline.parameters.partner >>
      - run: echo appassemble${PARTNER_FLAVOR}


workflows:
  sample:
    jobs:
      - building-jobs:
          name: "Building Number1"
          PARTNER_FLAVOR: "Number1"
      - building-jobs:
          name: "Building Number2"
          PARTNER_FLAVOR: "Number2"
