version: 2.1

orbs:
  python: circleci/python@1.4


jobs:
  building-jobs:
    parameters:
      partner:
        type: string
        default: "Number1"
      env:
        type: string
        default: "one"
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: echo "Building app for " << parameters.partner >>
      - run: echo appassemble${<< parameters.partner >>}


workflows:
  sample:
    jobs:
      - building-jobs:
          name: "Building Number1"
          partner: "Number1"
          env: "one"
      - building-jobs:
          name: "Building Number2"
          partner: "Number2"
          env: "two"
