version: 2.1

orbs:
  python: circleci/python@1.4


jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    parallelism: 2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
            mkdir test-results
            pytest --junitxml=test-results/junit.xml


workflows:
  sample:
    jobs:
      - build-and-test
